version: '3.8'
services:
  web-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - '3002:3002'
    volumes:
      - .:/usr/app
      - /usr/app/node_modules/
  web-prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - '8082:80'
